mutation CreateVehicle($params: CreateVehicleInput!) {
  createVehicle(params: $params) {
    message
    data {
      id
      registrationNumber
      capacity
      type
      transporterId
      transporter {
        id
        name
      }
      createdAt
      updatedAt
    }
  }
}

query GetVehicleById($id: UUID!) {
  vehicle(id: $id) {
    id
    registrationNumber
    capacity
    type
    transporterId
    transporter {
      id
      name
    }
    createdAt
    updatedAt
  }
}

query GetVehicles($query: QueryParams) {
  vehicles(query: $query) {
    items {
      id
      registrationNumber
      capacity
      type
      transporterId
      transporter {
        id
        name
      }
      createdAt
      updatedAt
    }
    meta {
      totalItems
    }
  }
}

mutation DeleteVehicleById($id: UUID!) {
  deleteVehicle(id: $id) {
    message
  }
}

mutation UpdateVehicle($id: UUID!, $params: UpdateVehicleInput!) {
  updateVehicle(id: $id, params: $params) {
    message
    data {
      id
      registrationNumber
      capacity
      type
      transporterId
      transporter {
        id
        name
      }
      createdAt
      updatedAt
    }
  }
}
