mutation CreateRole(
  $params: CreateRoleInput!
) {
  createRole(
    params: $params
  ) {
    message
    data {
      id
    }
  }
}

query GetRoleById($id: UUID!) {
  role(id: $id) {
    id
    name
    permissions {
      id
      name
    }
  }
}

query GetRoleByIdWithPermission($id: UUID!) {
  role(id: $id) {
    id
    name
    permissions {
      id
      name
    }
  }
}

query GetRoles($query: QueryParams) {
  roles(query: $query) {
    items {
      id
      name
    }
    meta {
      totalItems
    }
  }
}

mutation GivePermissionsToRole(
  $permissions: [SelectCategory]
  $roleId: String
) {
  givePermissionsToRole(permissions: $permissions, roleId: $roleId) {
    message
  }
}

mutation DeleteRoleById($id: UUID!) {
  deleteRole(id: $id) {
    message
  }
}

mutation UpdateRole($id: UUID!, $params: UpdateRoleInput) {
  updateRole(
    id: $id
    params: $params
  ) {
    message
    data {
      id
    }
  }
}
