mutation CreateUser($params: CreateUserInput!) {
  createUser(params: $params) {
    message
    data {
      id
    }
  }
}

mutation UpdateUser($id: UUID! $params: UpdateUserInput!) {
  updateUser(id: $id, params: $params) {
    message
    data {
      id
    }
  }
}

query GetUserById($id: UUID!) {
  user(id: $id) {
    phone
    id
    email
    firstName
    lastName
    profilePhotoLink
    createdAt
    roles {
      id
      role {
        id
        name
      }
      station {
        id
        name
      }
    }
  }
}

query GetUsers($query: QueryParams) {
  users(query: $query) {
    items {
      id
      firstName
      lastName
      email
      phone
    }
    meta {
      totalItems
    }
  }
}

mutation AssignRolesToUser(
  $roles: [UserRoleInput]!
  $userId: String!
) {
  assignRoleToUser(roles: $roles, userId: $userId) {
    message
  }
}

mutation DeleteUserById($id: UUID!) {
  deleteUser(id: $id) {
    message
  }
}

query UserWithRoles($userId: UUID!) {
  user(id: $userId) {
    phone
    id
    email
    firstName
    lastName
    profilePhotoLink
    createdAt
  }
  userRoles(userId: $userId) {
    items {
      id
      name
      permissions {
        id
        name
      }
    }
    meta {
      totalItems
    }
  }
}

#mutation AssignCountriesLanguagesToUser($userId: Int!, $countriesLanguages: [CountriesLanguagesInput!]!) {
#  assignCountriesLanguagesToUser(userId: $userId, countriesLanguages: $countriesLanguages) {
#    message
#  }
#}
#
#mutation AllocateWarehouse($userId: Int!, $warehouses: [SelectCategory!]!) {
#  allocateWarehouseToUser(userId: $userId, warehouses: $warehouses) {
#    message
#  }
#}

query GetUserCount {
  userCount {
    count
  }
}
