mutation CreateDriver($params: CreateDriverInput!) {
  createDriver(params: $params) {
    message
    data {
      id
      name
      licenseNumber
      contactNumber
      transporterId
      transporter {
        id
        name
      }
      createdAt
      updatedAt
    }
  }
}

query GetDriverById($id: UUID!) {
  driver(id: $id) {
    id
    name
    licenseNumber
    contactNumber
    transporterId
    transporter {
      id
      name
    }
    createdAt
    updatedAt
  }
}

query GetDrivers($query: QueryParams) {
  drivers(query: $query) {
    items {
      id
      name
      licenseNumber
      contactNumber
      transporterId
      transporter {
        id
        name
      }
      createdAt
      updatedAt
    }
    meta {
      totalItems
    }
  }
}

mutation DeleteDriverById($id: UUID!) {
  deleteDriver(id: $id) {
    message
  }
}

mutation UpdateDriver($id: UUID!, $params: UpdateDriverInput!) {
  updateDriver(id: $id, params: $params) {
    message
    data {
      id
      name
      licenseNumber
      contactNumber
      transporterId
      transporter {
        id
        name
      }
      createdAt
      updatedAt
    }
  }
}
