mutation CreateTransporter($params: CreateTransporterInput!) {
  createTransporter(params: $params) {
    message
    data {
      id
      name
      contactPerson
      contactNumber
      createdAt
      updatedAt
    }
  }
}

query GetTransporterById($id: UUID!) {
  transporter(id: $id) {
    id
    name
    contactPerson
    contactNumber
    drivers {
      id
      user {
        firstName
        lastName
        phone
        email
      }
      licenseNumber
    }
    vehicles {
      id
      registrationNumber
      capacity
      type
    }
    createdAt
    updatedAt
  }
}

query GetTransporters($query: QueryParams) {
  transporters(query: $query) {
    items {
      id
      name
      contactPerson
      contactNumber
      createdAt
      updatedAt
    }
    meta {
      totalItems
    }
  }
}

mutation DeleteTransporterById($id: UUID!) {
  deleteTransporter(id: $id) {
    message
  }
}

mutation UpdateTransporter($id: UUID!, $params: UpdateTransporterInput!) {
  updateTransporter(id: $id, params: $params) {
    message
    data {
      id
      name
      contactPerson
      contactNumber
      createdAt
      updatedAt
    }
  }
}
