fragment transporterVehicles on TransporterModel {
  vehicles {
    id
    registrationNumber
    capacity
    type
  }
}
fragment transporterDrivers on TransporterModel {
  drivers {
    id
    vehicles {
      id
      registrationNumber
    }
    user {
      id
      firstName
      lastName
      phone
      email
    }
    licenseNumber
  }
}
mutation CreateTransporter($params: CreateTransporterInput!) {
  createTransporter(params: $params) {
    message
    data {
      id
      name
      contactPerson
      phone
      createdAt
      updatedAt
    }
  }
}

query GetTransporterById($id: UUID!) {
  transporter(id: $id) {
    id
    name
    contactPerson
    phone
    createdAt
    updatedAt
    ...transporterDrivers
    ...transporterVehicles
  }
}

query GetTransporters($query: QueryParams) {
  transporters(query: $query) {
    items {
      id
      name
      contactPerson
      phone
      createdAt
      updatedAt
    }
    meta {
      totalItems
    }
  }
}

mutation DeleteTransporterById($id: UUID!) {
  deleteTransporter(id: $id) {
    message
  }
}

mutation UpdateTransporter($id: UUID!, $params: UpdateTransporterInput!) {
  updateTransporter(id: $id, params: $params) {
    message
    data {
      id
      name
      contactPerson
      phone
      createdAt
      updatedAt
    }
  }
}
