'use strict';
const { v4: uuid } = require('uuid');
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('brands', [
      {
        id: uuid(),
        name: 'AFRICAN GAS AND OIL COMPANY LIMITED',
        company_name: 'AFRICAN GAS AND OIL COMPANY LIMITED - Miritini, Mombasa',
        licence_number: 'ERC/LPG/1406',
        licence_description: 'Storage & Filling of LPG in Bulk',
        licence_expiry: new Date('2020-04-05'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'ALFA GAS LIMITED',
        company_name:
          'ALFA GAS LIMITED - Embakasi South - Nairobi, Enterprise Road',
        licence_number: 'ERC/LPG/673',
        licence_description: 'Storage & Filling of LPG in Bulk',
        licence_expiry: new Date('2020-08-21'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'AMEKEN MINEWEST COMPANY LIMITED',
        company_name: 'AMEKEN MINEWEST COMPANY LIMITED - Thika',
        licence_number: 'ERC/LPG/1528',
        licence_description: 'Storage and filling of LPG in Cylinders',
        licence_expiry: new Date('2019-09-13'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'AVIAN GAS LIMITED',
        company_name: 'AVIAN GAS LIMITED - Masai Rd Off Mombasa Rd',
        licence_number: 'ERC/LPG/1299',
        licence_description: 'Storage and filling of LPG in Cylinders',
        licence_expiry: new Date('2019-12-02'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'BOC KENYA LIMITED',
        company_name: 'BOC KENYA LIMITED - Nairobi, Kitui Road',
        licence_number: 'ERC/LPG/1042',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-09-05'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'CAPITAL GAS CONSUMER COOPERATIVE SOCIETY',
        company_name:
          'CAPITAL GAS CONSUMER COOPERATIVE SOCIETY - Embakasi East, Eastern Bypass',
        licence_number: 'ERC/LPG/1636',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-11'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'CHEMIGAS LTD',
        company_name: 'CHEMIGAS LTD - Kitui',
        licence_number: 'ERC/LPG/1756',
        licence_description: 'Storage & Filling of LPG in Bulk',
        licence_expiry: new Date('2020-07-03'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'CHEV ENERGIES LIMITED',
        company_name: 'CHEV ENERGIES LIMITED - Webuye',
        licence_number: 'ERC/LPG/1526',
        licence_description: 'Storage and filling of LPG in Cylinders',
        licence_expiry: new Date('2020-09-05'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'CITY GAS LIMITED',
        company_name: 'CITY GAS LIMITED - Kisii',
        licence_number: 'ERC/LPG/1821',
        licence_description: 'Storage & Filling of LPG in Bulk',
        licence_expiry: new Date('2020-09-05'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'CITY GAS LIMITED',
        company_name: 'CITY GAS LIMITED - Nairobi East, Lusaka Road',
        licence_number: 'ERC/LPG/1183',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-04-15'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'CRESCENT ENERGY LIMITED',
        company_name: 'CRESCENT ENERGY LIMITED - Kiambu, Kikuyu road',
        licence_number: 'ERC/LPG/1101',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-01-22'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'DEPAR LIMITED',
        company_name: 'DEPAR LIMITED - Old North Airport Road',
        licence_number: 'ERC/LPG/1510',
        licence_description: 'Storage and filling of LPG in Cylinders',
        licence_expiry: new Date('2020-09-05'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'DEPAR LIMITED',
        company_name: 'DEPAR LIMITED - Sagana, Kirinyaga - Muranga Road',
        licence_number: 'ERC/LPG/1277',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-14'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'ECO-ENERGY EAST AFRICA LIMITED',
        company_name: 'ECO-ENERGY EAST AFRICA LIMITED - Nairobi, Lunga Lunga',
        licence_number: 'ERC/LPG/1319',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'ENERGY HORIZONS',
        company_name: 'ENERGY HORIZONS - Factory Street, Thika',
        licence_number: 'ERC/LPG/1603',
        licence_description: 'Storage and filling of LPG in Cylinders',
        licence_expiry: new Date('2019-12-19'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'EXCELLENT LOGISTICS LTD',
        company_name: 'EXCELLENT LOGISTICS LTD - Laikipia, Nyeri - Nyahururu',
        licence_number: 'ERC/LPG/1444',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-05-23'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'FAST GAS LIMITED',
        company_name: 'FAST GAS LIMITED - Nairobi, Shimo la tewa',
        licence_number: 'ERC/LPG/1222',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-04'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'FOSSIL FUELS LIMITED',
        company_name: 'FOSSIL FUELS LIMITED - Mombasa',
        licence_number: 'ERC/LPG/1524',
        licence_description: 'Storage and filling of LPG in Cylinders',
        licence_expiry: new Date('2019-09-12'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'GICOMU GAS LIMITED',
        company_name: 'GICOMU GAS LIMITED - Embu',
        licence_number: 'ERC/LPG/1643',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-14'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'GREATMOUNT LPG LIMITED',
        company_name: 'GREATMOUNT LPG LIMITED - Naromoru, Nyeri-Nanyuki RD',
        licence_number: 'ERC/LPG/1639',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-12'),
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('brands', null, {});
  },
};
