'use strict';
const { v4: uuid } = require('uuid');

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('brands', [
      {
        id: uuid(),
        name: 'African Gas',
        company_name: 'African Gas and Oil Company Limited - Miritini, Mombasa',
        licence_number: 'ERC/LPG/1406',
        licence_description: 'Storage & Filling of LPG in Bulk',
        licence_expiry: new Date('2020-04-05'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Alfa Gas',
        company_name: 'Alfa Gas Limited - Embakasi South - Nairobi, Enterprise Road',
        licence_number: 'ERC/LPG/673',
        licence_description: 'Storage & Filling of LPG in Bulk',
        licence_expiry: new Date('2020-08-21'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Ameken Gas',
        company_name: 'Ameken Minewest Company Limited - Thika',
        licence_number: 'ERC/LPG/1528',
        licence_description: 'Storage and filling of LPG in Cylinders',
        licence_expiry: new Date('2019-09-13'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Avian Gas',
        company_name: 'Avian Gas Limited - Masai Rd Off Mombasa Rd',
        licence_number: 'ERC/LPG/1299',
        licence_description: 'Storage and filling of LPG in Cylinders',
        licence_expiry: new Date('2019-12-02'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Boc Gas',
        company_name: 'Boc Kenya Limited - Nairobi, Kitui Road',
        licence_number: 'ERC/LPG/1042',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-09-05'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Capital Gas',
        company_name: 'Capital Gas Consumer Cooperative Society - Embakasi East, Eastern Bypass',
        licence_number: 'ERC/LPG/1636',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-11'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Chemigas Gas',
        company_name: 'Chemigas Ltd - Kitui',
        licence_number: 'ERC/LPG/1756',
        licence_description: 'Storage & Filling of LPG in Bulk',
        licence_expiry: new Date('2020-07-03'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Chev Gas',
        company_name: 'Chev Energies Limited - Webuye',
        licence_number: 'ERC/LPG/1526',
        licence_description: 'Storage and filling of LPG in Cylinders',
        licence_expiry: new Date('2020-09-05'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'City Gas',
        company_name: 'City Gas Limited - Kisii',
        licence_number: 'ERC/LPG/1821',
        licence_description: 'Storage & Filling of LPG in Bulk',
        licence_expiry: new Date('2020-09-05'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Crescent Gas',
        company_name: 'Crescent Energy Limited - Kiambu, Kikuyu road',
        licence_number: 'ERC/LPG/1101',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-01-22'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Depar Gas',
        company_name: 'Depar Limited - Sagana, Kirinyaga - Muranga Road',
        licence_number: 'ERC/LPG/1277',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-14'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Eco Gas',
        company_name: 'Eco-Energy East Africa Limited - Nairobi, Lunga Lunga',
        licence_number: 'ERC/LPG/1319',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Energy Gas',
        company_name: 'Energy Horizons - Factory Street, Thika',
        licence_number: 'ERC/LPG/1603',
        licence_description: 'Storage and filling of LPG in Cylinders',
        licence_expiry: new Date('2019-12-19'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Excellent Gas',
        company_name: 'Excellent Logistics Ltd - Laikipia, Nyeri - Nyahururu',
        licence_number: 'ERC/LPG/1444',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-05-23'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Fast Gas',
        company_name: 'Fast Gas Limited - Nairobi, Shimo la tewa',
        licence_number: 'ERC/LPG/1222',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-04'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Fossil Gas',
        company_name: 'Fossil Fuels Limited - Mombasa',
        licence_number: 'ERC/LPG/1524',
        licence_description: 'Storage and filling of LPG in Cylinders',
        licence_expiry: new Date('2019-09-12'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Gicomu Gas',
        company_name: 'Gicomu Gas Limited - Embu',
        licence_number: 'ERC/LPG/1643',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-14'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: uuid(),
        name: 'Greatmount Gas',
        company_name: 'Greatmount LPG Limited - Naromoru, Nyeri-Nanyuki RD',
        licence_number: 'ERC/LPG/1639',
        licence_description: 'Storage & Filling of LPG in Cylinders',
        licence_expiry: new Date('2020-02-12'),
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('brands', null, {});
  },
};
