export enum PermissionsEnum {
  CreateUser = 'create user',
  DeleteUser = 'delete user',
  UpdateUser = 'update user',
  CreateRole = 'create role',
  DeleteRole = 'delete role',
  UpdateRole = 'update role',
  CreatePermission = 'create permission',
  DeletePermission = 'delete permission',
  UpdatePermission = 'update permission',
  GivePermissionToRole = 'give permission to role',
  AssignRoleToUser = 'assign role to user',
  CreateOtp = 'create otp',
  DeleteOtp = 'delete otp',
  UpdateOtp = 'update otp',
  CreatePasswordReset = 'create password-reset',
  DeletePasswordReset = 'delete password-reset',
  UpdatePasswordReset = 'update password-reset',
  CreateNotification = 'create notification',
  DeleteNotification = 'delete notification',
  UpdateNotification = 'update notification',
  MarkNotificationAsRead = 'mark notification as read',
  CreateSetting = 'create setting',
  DeleteSetting = 'delete setting',
  UpdateSetting = 'update setting',
  CreateActivityLog = 'create activity log',
  DeleteActivityLog = 'delete activity log',
  UpdateActivityLog = 'update activity log',
  CreateBrand = 'create brand',
  DeleteBrand = 'delete brand',
  UpdateBrand = 'update brand',

}
