fragment orderDealerFragment on OrderModel {
  dealer {
    id
    name
  }
}

fragment dispatchDealerFragment on OrderModel {
  dispatchStatus
  dispatch {
    id
    status
    driver {
      id
      user {
        firstName
        lastName
        phone
      }
    }
    transporter {
      id
      name
    }
    vehicle {
      id
      registrationNumber
    }

  }
}
mutation CreateOrder(
  $params: CreateOrderInput!
) {
  createOrder(
    params: $params
  ) {
    message
    data {
      id
    }
  }
}

query GetOrderById($id: UUID!) {
  order(id: $id) {
    id
  }
}

query GetOrders(
  $query: QueryParams,
  $includeDealer: Boolean = true
  $includeDispatch: Boolean = true
) {
  orders(query: $query) {
    items {
      id
      createdAt
      totalPrice
      status
      depot {
        name
      }
      ...orderDealerFragment @include(if: $includeDealer)
      ...dispatchDealerFragment @include(if: $includeDispatch)
      items {
        id
        quantity
        catalogue {
          pricePerUnit
          quantityPerUnit
          unit
          id
          name
        }
      }
    }
    meta {
      totalItems
    }
  }
}

mutation DeleteOrderById($id: UUID!) {
  deleteOrder(id: $id) {
    message
  }
}

mutation UpdateOrder($id: UUID!, $params: UpdateOrderInput!) {
  updateOrder(
    id: $id
    params: $params
  ) {
    message
    data {
      id
    }
  }
}

mutation UpdateOrderStatus($id: UUID!, $params: UpdateOrderStatusInput!) {
  updateOrderStatus(id: $id, params: $params) {
    message
    data {
      id
      status
    }
  }
}
