export enum DriverInventoryStatus {
  // Filled Canisters Flow
  FILLED_ASSIGNED = 'FILLED_ASSIGNED',
  FILLED_IN_TRANSIT = 'FILLED_IN_TRANSIT',
  FILLED_DELIVERED = 'FILLED_DELIVERED',
  
  // Empty Canisters Flow
  EMPTY_COLLECTED = 'EMPTY_COLLECTED',
  EMPTY_IN_TRANSIT = 'EMPTY_IN_TRANSIT',
  EMPTY_RETURNED = 'EMPTY_RETURNED'
}
