fragment notificationItem on NotificationUserModel {
  id
  description
  createdAt
  title
  isRead
}

query GetAuthenticatedUserNotifications(
  $pageSize: Int!
  $currentPage: Int!
  $filters: [QueryParamsFilter]
) {
  authenticatedUserNotifications(
    query: {
      sortBy: "createdAt"
      sortByDirection: DESC
      pageSize: $pageSize
      currentPage: $currentPage
      filters: $filters
    }
  ) {
    items {
      ...notificationItem
    }
    meta {
      totalItems
    }
  }
}



query GetAuthenticatedUserNotificationStats {
  authenticatedUserNotificationStats {
    unread
    read
    total
  }
}

mutation MarkNotificationAsRead($notifications: [SelectCategory!]!) {
  markNotificationAsRead(notifications: $notifications) {
    message
    data {
      read
      unread
      total
    }
  }
}

subscription NotificationCreatedTrack {
  notificationCreated {
    notification {
      ...notificationItem
    }
    stats {
      unread
      read
      total
    }
  }
}
