mutation CreatePermission(
  $params: CreatePermissionInput!
) {
  createPermission(
    params: $params
  ) {
    message
    data {
      id
    }
  }
}

query GetPermissionById($id: UUID!) {
  permission(id: $id) {
    id
    name
  }
}

query GetPermissions($query: QueryParams) {
  permissions(query: $query) {
    items {
      id
      name
    }
    meta {
      totalItems
    }
  }
}

mutation DeletePermissionById($id: UUID!) {
  deletePermission(id: $id) {
    message
  }
}
