fragment cartFragment on CartModel {
  id
  totalQuantity
  totalPrice
  items {
    id
    catalogueId
    quantity
    catalogue {
      id
      name
      pricePerUnit
      unit
      quantityPerUnit
    }
  }
}

query GetCarts($query: QueryParams) {
  carts(query: $query) {
    items { ...cartFragment }
    meta {
      totalItems
    }
  }
}
query GetCart($id: UUID!) { cart(id: $id) { ...cartFragment }}

mutation CreateCart($params: CreateCartInput) {
  createCart(params: $params) {
    message
    data { ...cartFragment }
  }
}

mutation AddItemToCart($cartId: UUID, $inventoryId: UUID!, $quantity: Int!) {
  addItemToCart(cartId: $cartId, inventoryId: $inventoryId, quantity: $quantity) {
    message
    data { ...cartFragment }
  }
}

mutation RemoveItemFromCart($cartId: UUID!, $cartCatalogueId: UUID!) {
  removeItemFromCart(cartId: $cartId, cartCatalogueId: $cartCatalogueId) {
    message
    data { ...cartFragment }
  }
}

mutation UpdateItemQuantity($cartId: UUID!, $cartCatalogueId: UUID!, $quantity: Int!) {
  updateItemQuantity(cartId: $cartId, cartCatalogueId: $cartCatalogueId, quantity: $quantity) {
    message
    data { ...cartFragment }
  }
}

mutation CompleteCart($cartId: UUID!) {
  completeCart(cartId: $cartId ) {
    message
    data {
      id
    }
  }
}
